machine:
  network:
    hostname: controlplane
    interfaces:
      - interface: enxdca63208e2ac
        addresses:
          - 192.168.0.100/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.0.1
        dhcp: true
  install:
    disk: /dev/mmcblk0
    wipe: false

# cluster:
#   cni:
#     name: none